#!/bin/sh /etc/rc.common
# Watches FRR's VRRP state and moves the LAN default route accordingly.
# See /usr/sbin/vrrp-route-failover.sh. Starts after frr (START=95).

START=96
USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /usr/sbin/vrrp-route-failover.sh
	procd_set_param respawn
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}
