# SPDX-License-Identifier: GPL-2.0
# Out-of-tree build. Mirrors the upstream Makefile with obj-m so the
# tree can be built against installed kernel headers on the test box.
obj-m	+= prestera.o
prestera-objs	:= prestera_main.o prestera_hw.o prestera_dsa.o \
		   prestera_rxtx.o prestera_devlink.o prestera_ethtool.o \
		   prestera_switchdev.o prestera_acl.o prestera_flow.o \
		   prestera_flower.o prestera_span.o prestera_counter.o \
		   prestera_router.o prestera_router_hw.o prestera_matchall.o

obj-m	+= prestera_pci.o
